"""Compare random-init FM vs SSL warm-start FM, averaged over multiple seeds.

Reuses baseline.py::run_fm()'s exact training loop (same epochs/patience/early-stop
logic) so the only difference between the two runs is how V is initialized —
any score gap is attributable to SSL pretraining itself, not training-loop differences.

Prerequisite: run ssl_pretrain.py first to generate ssl_video_emb.npy.

Usage:
    python3 ssl_compare.py [data_dir] [--ssl_emb ssl_video_emb.npy] [--seeds 3]
"""
import argparse, statistics
import numpy as np
from data import load, field_layout, FIELDS
import baseline as B


def summarize(name, results):
    g = statistics.mean(r['GAUC'] for r in results)
    n5 = statistics.mean(r['nDCG@5'] for r in results)
    pr = statistics.mean(r['primary'] for r in results)
    sd = statistics.pstdev([r['primary'] for r in results]) if len(results) > 1 else 0.0
    print(f"  {name:20s} | test GAUC {g:.4f} | nDCG@5 {n5:.4f} | primary {pr:.4f} ± {sd:.4f}")
    return pr


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('data_dir', nargs='?', default='./KuaiRand-Pure/data')
    ap.add_argument('--ssl_emb', default='ssl_video_emb.npy')
    ap.add_argument('--seeds', type=int, default=3)
    ap.add_argument('--k', type=int, default=16)
    ap.add_argument('--epochs', type=int, default=40)
    a = ap.parse_args()

    print(f"loading {a.data_dir} ...")
    splits = load(a.data_dir)
    _, field_dims, offsets = field_layout(splits['train'])
    vi = FIELDS.index('video_id')
    lo, hi = int(offsets[vi]), int(offsets[vi] + field_dims[vi])
    dim = int(sum(field_dims))

    ssl_emb = np.load(a.ssl_emb)
    expected_shape = (hi - lo, a.k)
    assert ssl_emb.shape == expected_shape, (
        f"ssl_video_emb.npy shape {ssl_emb.shape} != expected {expected_shape} "
        f"-- must be generated by ssl_pretrain.py on the same data_dir, with matching --k")

    def make_ssl_V(seed):
        """Random-init the full V table, then overwrite the video_id slice with
        the SSL-pretrained embeddings. Non-video fields (user_id/author_id/tab/
        dur_bucket) stay randomly initialized -- isolates "only video's starting
        point changed" as the single variable being tested."""
        rng = np.random.default_rng(seed)
        V = rng.normal(0, 0.01, (dim, a.k)).astype(np.float32)
        V[lo:hi] = ssl_emb
        return V

    seeds = list(range(a.seeds))
    print(f"\nrunning {a.seeds} seed(s) x 2 variants (each up to {a.epochs} epochs, early-stop patience=4) ...\n")

    print("random-init FM:")
    rand_results = [B.run_fm(splits, k=a.k, epochs=a.epochs, seed=s, verbose=False) for s in seeds]
    pr_rand = summarize("random-init", [r['test'] for r in rand_results])

    print("\nSSL warm-start FM:")
    ssl_results = [B.run_fm(splits, k=a.k, epochs=a.epochs, seed=s, verbose=False, init_V=make_ssl_V(s))
                    for s in seeds]
    pr_ssl = summarize("SSL warm-start", [r['test'] for r in ssl_results])

    print(f"\nDelta primary (SSL - random) = {pr_ssl - pr_rand:+.4f}")
    print("(official FM baseline in baseline_scores.json: test primary 0.5946, std 0.0008 over 5 seeds -- "
          "use that as a sanity check that the random-init run above lands close to it)")
